name: CI
on: push

jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v1
#      - run: npm install
#      - run: npm test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'  # 指定要使用的 Node.js 版本
      - run: npm install
      - run: npm run build
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ibackchina2018/vue-act:latest